---
title: "Derivatives, Plots, Git"
format: html
editor: visual
---

## Derivatives in R

```{r}
library(tidyverse)
library(palmerpenguins)
usethis::use_git()
usethis::use_github()
```

```{r}
#Find the slope of f(x)=x2 at x=3
Df <- D(expression(x^2),'x')
x=3
eval(Df)
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
         geom_point(aes(color = species)) +
  scale_color_manual(values = c("purple","cyan3","goldenrod")) +
  labs(x = "Bill length (mm)",
       y = "Bill depth (mm)",
       title = "Palmer penguin bill size measurements",
       subtitle = "Palmer Archipelago, Antarctica (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleages at Palmer Station LTER") +
  theme_minimal()
```

```{r}
print(colnames(penguins))
```

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
         geom_jitter(aes(color = species)) +
  scale_color_manual(values = c("purple","cyan3","goldenrod")) +
  labs(x = "Species",
       y = "Flipper legth (mm)",
       title = "Palmer penguin flipper size measurements",
       subtitle = "Palmer Archipelago, Antarctica (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleages at Palmer Station LTER") +
  theme_minimal()
```
